### ISSUE TITLE
FEATURE: Select one of sequences as reference (i.e. not cyclically shifted )

### ISSUE THREAD

**Issue by AlesBucek** [lorrainea/MARS#10]
Hi! Thanks for sharing such a great tool!
This is a feature suggestion not an issue:
It would be really nice if one sequence can be selected as reference (i.e. it is not cyclically shifted) and all other sequences would shift "around" it. 
Without this functionality it is not possible to decide which region of the sequences will be the start/end of the alignment. 

More specifically what I have in mind: I was using MARS to build alignments of circular DNA molecules which are "opened" in different regions. There is a conveention which region of the circular DNA is "origin" and it would be great to have one sequence with "origin" at the 5'-end which would determine the arrangement of the remaining cyclically shifted molecules.

Cheers!
Ales

**Comment by lorrainea** [comment]
Hi

MARS was designed in mind that the 'starting' position in all of the sequences is unknown. However, it would be interesting to incorporate this in some way. 

We have another tool [hCED](https://github.com/lorrainea/hCED) that does a pairwise comparison of cyclic sequences and the second sequence in the input FASTA file is left unrotated, meaning it could be used as a reference sequence. The only limit of hCED in relation to this feature you suggest, is that it does pairwise comparison only, so you would need to do a few runs depending on how many sequences are in your input file, and just always keep the reference sequence as the second sequence in all the input files in all the runs.

Lorraine

**Comment by AlesBucek** [comment]
Hi Lorraine,
hCED looks great - thx for the suggestion! It will indeed require one run per sequence but it is a good alternative the other option I had in mind: splitting the multiple alignment of the MARSed sequences between what is intended to be a 3-end and 5-end.

Cheers, Ales
