### ISSUE TITLE
missing divsufsort.h for installation

### ISSUE THREAD

**Issue by xiaoyunguo** [lorrainea/MARS#11]
Hi,

I am trying to install MARS for circular sequence alignment in Ubuntu. But I got the complain of 
sacsc.cc:29:10: fatal error: divsufsort.h: No such file or directory

   29 | #include <divsufsort.h>                                           // include header for suffix sort
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:25: sacsc.o] Error 1

Any suggestions?
 
Thanks

**Comment by lorrainea** [comment]
Did you run ./pre-install.sh first?
