### ISSUE TITLE
contains an unexpected character

### ISSUE THREAD

**Issue by ejna1212** [lorrainea/MARS#12]
Hello, 

I am trying to run MARs using multiple circovirus genomes (DNA sequences). Each sequence is composed of A, T, G, and C, and some sequences also include N in the middle. 
However, when I try to run my FASTA file in MARS, it gives an error message saying "contains an unexpected character".

Running the command as shown in the examples, "./mars -a DNA -m 0 -i ./data/10.gappy.fasta -o ./data/10.gappy.output.fasta -q 5 -l 20 -P 1," works. However, when I try to run "mammals.bear.fas" in the "exp2" folder, I encounter the same "contains an unexpected character" error.
What are differences between "mammals.fas" and "mammals.bear.fas" ?

Also, how do I modify my file to make it?

Thank you!

**Comment by lorrainea** [comment]
Hello, I have run MARS with the mammals.bear.fas file (although this is technically an already rotated set output by the BEAR tool) it should still be able to run and successfully does for myself. I suspect this is an encoding issue and wanted to point you to this thread to see if the last comment solves your problem https://github.com/lorrainea/MARS/issues/2.

Regards
Lorraine
