### ISSUE TITLE
Reverse Complement and Circular alignement

### ISSUE THREAD

**Issue by Phismil** [lorrainea/MARS#13]
Dear Lorraine
Thank you for maintaing and updating the repository.
I have a question that need your kind advise and your expertise:
How does MARS deal with re-orientation when all circular genomes are not in the same orientation and some are in the reverse complement direction?
Many thanks in advance

**Comment by lorrainea** [comment]
Hi, you would need to first make sure all sequences are in the same orientation before inputting them into MARS.
