### ISSUE TITLE
Segmentation fault with "-m1 1" option

### ISSUE THREAD

**Issue by chris-rands** [lorrainea/MARS#3]
When running this command I get a Segmentation fault, but only when I add the `-m 1` flag;

```
$ mars -m 1 -a DNA -i test.fa -o testout.fa
 Reading the (Multi)FASTA input file: test.fa
 Computing cyclic edit distance for all sequence pairs
Segmentation fault
```

I want to try with this option to improve the accuracy of the rotation since the output is not correct with `-m 0`. My input fasta file has 2 sequences of ~40kb in length.

Thank you!

**Comment by lorrainea** [comment]
Hi

Could you please send over your input files so I can understand more about where the issue is coming from.

Thanks

**Comment by chris-rands** [comment]
Sure, thank you, the input file is here:

ftp://cegg.unige.ch/rands/test_seqs/test.fa

**Comment by lorrainea** [comment]
There seems to be an issue with the sequence length and the branch and bound method. I will need to look at this properly another time, but for now seeing as you are working with two sequences only you can make use of hCED - this tool is used by MARS anyway when computing the distance between the sequence pairs: https://github.com/lorrainea/hCED

**Comment by chris-rands** [comment]
Ok thanks!

**Comment by lorrainea** [comment]
Branch and bound code updated - However you will most likely need to use external memory for large sequences such as these.
