### ISSUE TITLE
Segmentation fault with any setup

### ISSUE THREAD

**Issue by GiulioF1** [lorrainea/MARS#4]
Dear colleagues,

I am trying to use MARS to align DNA sequences. Apparently both the software and the dependencies where successfully installed. However, when I try to run it either on my own data set (a very simple one) or even using your example:

https://github.com/lorrainea/MARS/blob/master/EXAMPLES

I get the following:

```
(base) -bash-4.1$ mars -a DNA -m 0 -i 10.gappy.fasta -o 10.gappy.output.fasta -q 5 -l 20 -P 1

 Reading the (Multi)FASTA input file: 10.gappy.fasta

 Computing cyclic edit distance for all sequence pairs

Segmentation fault
```

I have seen someone else had the same issue both his solution would not work for me as I have to align multiple sequences.

I have also tried adding more cores with -T 16 but it didn't help. It looks like it's trying to use resources it should not use. Or there's maybe an error in the files (even those from your github rep).

Can you help me?

Many thanks in advance.

**Comment by lorrainea** [comment]
Hi, thanks for pointing this out. You should be able to run commands as normal now.

**Comment by GiulioF1** [comment]
Thank you very much. This apparently solved the issue. Best
