### ISSUE TITLE
Issue when run the program

### ISSUE THREAD

**Issue by Vladislav-Shevtsov** [lorrainea/MARS#6]
I am trying to run the program - `./mars -i /mnt/d/Linux/fish.fasta -a DNA -m 1 -o /mnt/d/Linux/`
which gives me following result: 
```
Reading the (Multi)FASTA input file: /mnt/d/Linux/fish.fasta
!Error: input file /mnt/d/Linux/fish.fasta contains an unexpected char

acter
```
The fasta file is attached as .txt file
[fastafile.txt](https://github.com/lorrainea/MARS/files/3562659/fastafile.txt)
. Thank you!

**Comment by lorrainea** [comment]
Hi
I copied and pasted your sequences into a new text file and this seems to have worked.
Let me know if you are still having any problems.
Lorraine

[input.fasta.txt](https://github.com/lorrainea/MARS/files/3562856/input.fasta.txt)

**Comment by Vladislav-Shevtsov** [comment]
Hi,
Thank you very much for such a quick response! I've tried to run the
program yesterday and looks like it works. I gives me a message  "Computing
cyclic edit distance for all sequence pairs". But  it took all day and
did't give me any result. My laptop is dell core i5 8th generation H series
, 8GB of ram. Is it supposed to take such a long time?
commands I've been using ./mars -i /mnt/d/Linux/input.fasta.txt -a DNA -m 1
-o inputrotate
and ./mars -i /mnt/d/Linux/input.fasta.txt -a DNA -m 1 -o /mnt/d/Linux

Best regards, Vladislav

**Comment by lorrainea** [comment]
Hi

You have 1259 sequences in your input file so it is expected that this part of the computation will take a long time...I would suggest trying the -m 0 option which will be faster but will still take a while to run.

Lorraine
