### ISSUE TITLE
Best values for q, l and P for chloroplast genomes

### ISSUE THREAD

**Issue by Silverfoxcome** [lorrainea/MARS#8]
Hi!!!I

I'm using mars to rotate my 15 chloroplast genomes of aprox. 140,000 bp in length. I was wondering what values for q, l and P would be the best for sequences of this length.

For now, I'm working with the default values but I don't think this is the best after reading the paper and the values for q, l and P that you used for mitochondrial genomes (of 15,000 bp).

Thank you so much in advance for your help  :)

**Comment by lorrainea** [comment]
Hi, I would use q=5, l=150, P=2.

Providing a small value for l increases accuracy but slows down computation and so l=150 seems reasonable here. The P parameter is like a final precision measure, but it would not make sense to increase this above 2.0 if l is smaller or equal to the square root of the sequence length.

You can attempt this set of parameters and see if it results in a more accurate multiple sequence alignment compared to the default parameters.

**Comment by Silverfoxcome** [comment]
> Hi, I would use q=5, l=150, P=2.
> 
> Providing a small value for l increases accuracy but slows down computation and so l=150 seems reasonable here. The P parameter is like a final precision measure, but it would not make sense to increase this above 2.0 if l is smaller or equal to the square root of the sequence length.
> 
> You can attempt this set of parameters and see if it results in a more accurate multiple sequence alignment compared to the default parameters.

I'll run it with those parameters then and compare them with the result it got with the default parameters!!! 

Thank you so much for your answer!!!!
