### ISSUE TITLE
Clustal options for alignment in command line to not lose MARS information

### ISSUE THREAD

**Issue by Silverfoxcome** [lorrainea/MARS#9]
Hello again!
Sorry to bother you again 
I installed the clustalo program in my linux system and I was looking at the options.
(I also submited my rotated sequences to https://www.ebi.ac.uk/Tools/msa/clustalo/ like you adviced but sometimes they said that my sequences are too long and that they can't do the job, that's why I installed the program).

I wanted to ask if you have experience with the correct options one should use **to not lose the information of the rotated sequences obtained with MARS** when using the clustalo program from the command line.

Looking at the options in my command line, I see:
--p1=<file> that allows you to put pre-aligned multiple sequence file (aligned columns will be kept fix), that is what I think MARS did. Pre-align my sequences.

So I was thinking of using the following command:
```
$ clustalo -i rotated.sequences.fasta -o msa.file.fasta or
$ clustalo -i multifasta.file.with.no.rotated.sequences.fasta --profile1=rotated.sequences.fasta -o msa.file.fasta
```

I'm following this guide (points a and c): http://www.clustal.org/omega/README

With (a):

> (a) ... If the sequences are aligned (all sequences
>     have the same length and at least one sequence has at least one
>     gap), then the alignment is turned into a HMM, the sequences are
>     de-aligned and the now un-aligned sequences are aligned using the
>     HMM as an External Profile for External Profile Alignment (EPA).
>     If no EPA is desired use the --dealign flag.

With (c):

> (c) one file with unaligned sequences (i) and one profile (ii); the
>     **profile (pre-aligned sequences)** is converted into a HMM and the un-aligned sequences will
>     be multiply aligned (using the HMM background information) to form
>     a profile; this constructed profile is aligned with the input
>     profile; the columns in each profile (the original one and the one
>     created from the un-aligned sequences) will be kept fixed and the
>     alignment of the two profiles will be written out. Use the -i flag
>     in conjunction with the --p1 flag for this mode.

**Once again, sorry to bother you and thanks for all the help.**

**Comment by lorrainea** [comment]
Hi, so the output of MARS will be rotated sequences. These are just simply accurate rotations for each sequence in your input dataset. Therefore no information about the alignment will be output by MARS.

So when using any type of multiple sequence alignment including clustal, the input will be simply your output from MARS. 

The correct command to use for Clustal Omega would be

$ clustalo -i rotated.sequences.fasta -o msa.file.fasta

This is because you are inputting unaligned sequences which clustal omega will then take and align to produce for you a multiple sequence alignment. 

I hope this answers your question.

**Comment by Silverfoxcome** [comment]
> Hi, so the output of MARS will be rotated sequences. These are just simply accurate rotations for each sequence in your input dataset. Therefore no information about the alignment will be output by MARS.
> 
> So when using any type of multiple sequence alignment including clustal, the input will be simply your output from MARS.
> 
> The correct command to use for Clustal Omega would be
> 
> $ clustalo -i rotated.sequences.fasta -o msa.file.fasta
> 
> This is because you are inputting unaligned sequences which clustal omega will then take and align to produce for you a multiple sequence alignment.
> 
> I hope this answers your question.

Yes! It does!!!
Thank you so much for your kind help :D
